version: "3.9"

services:
  main:
    container_name: misa198
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URL: 
      PORT: 3000
      NEXT_PUBLIC_APP_DOMAIN: http://localhost:3000
      APP_DOMAIN: http://localhost:3000
    expose:
      - 3000
    networks:
      - common

networks:
  common:
