version: "3.9"

services:
  main:
    container_name: misa198
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://localhost:27017/misa198
      NEXT_PUBLIC_APP_DOMAIN: http://localhost:3000
      APP_DOMAIN: http://localhost:3000
      NEXT_PUBLIC_GG_AN_ID:
      GG_AN_ID:
      FB_APP_ID:
      NEXT_PUBLIC_FB_APP_ID:
    expose:
      - 3000
    networks:
      - common

networks:
  common:
